# config/logging_config.yaml

version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  error:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s - %(pathname)s:%(lineno)d'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: logs/trading.log
    mode: a
    encoding: utf8

  error_file_handler:
    class: logging.FileHandler
    level: ERROR
    formatter: error
    filename: logs/error.log
    mode: a
    encoding: utf8

  trade_file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: logs/trades.log
    mode: a
    encoding: utf8

loggers:
  trading_bot:
    level: INFO
    handlers: [console, file_handler, error_file_handler]
    propagate: false

  trading_bot.trades:
    level: INFO
    handlers: [trade_file_handler]
    propagate: false

root:
  level: INFO
  handlers: [console, file_handler, error_file_handler]